[project]
name = "{{ petor.project.name }}"
version = "0.1.0"
description = "{{ petor.project.description }}"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
    "djangorestframework>=3.16.0",
]
